管理人画面のひな型を作成
Kobe-Spiral-2021-GroupA/santa-sanda-stamp-rally pull request #101
Opened 2021-08-15 11:23 UTC by oura-hideyoshi

## Issue

\# 49

## 概要

```Markdown
変更点や補足、レビュー時に特に見てほしい点などを記載
```
管理人画面のひな型を作成
- map
- spot
- task
それぞれの
- 閲覧
- 編集
- 作成
の機能を簡単に実装しました。

## PR 作成時のチェック項目

- [ ] PR 名は issue 名と同じにした
- [ ] 担当者として Assignees を設定した
- [ ] レビューを希望する人に Reviewers を設定した
- [ ] Labels から "PR: Main" ラベルを選択した

2021-08-30 08:03 UTC, narimatsutomoki commented
map編集画面に遷移すると、「戻る」「保存」ボタンが2つずつ表示されてます

2021-08-30 08:13 UTC, narimatsutomoki commented
各種ログはユーザ一覧から確認できる感じ？

2021-08-30 12:26 UTC, oura-hideyoshi commented
> map編集画面に遷移すると、「戻る」「保存」ボタンが2つずつ表示されてます



> map編集画面に遷移すると、「戻る」「保存」ボタンが2つずつ表示されてます

プログレスバー編集画面がそこに来るねん
まだ進捗関連がまだやから、枠だけ用意して置いといてる

2021-08-30 16:39 UTC, AkashiTakumi commented
コンフリクト起きてるからそれの解消と，あとテスト方法というか動作確認の仕方ってどっか書いてるかな？

2021-08-30 17:06 UTC, AkashiTakumi requested changes
マップ一覧は出るけど，管理者一覧とユーザ一覧を開いたら404になるのは仕様？

2021-08-31 02:00 UTC, oura-hideyoshi commented
restController用に、READMEに乗せたテンプレと
管理者画面用につけたREADMEのusageでコンフリクトやね
どっちも残したい（もしくは、restControllerの階層にREADMEを作成してもいいかも）

2021-08-31 02:03 UTC, oura-hideyoshi commented
@AkashiTakumi 
> マップ一覧は出るけど，管理者一覧とユーザ一覧を開いたら404になるのは仕様？
管理者一覧とユーザ一覧が不在なのは仕様
ログインやサインアップがないので、まだ作るべきじゃないかと判断してる








>  ~~コンフリクト起きてるからそれの解消と~~, あとテスト方法というか動作確認の仕方ってどっか書いてるかな？

管理者画面作成ブランチの、README参照
```
http://localhost:18080/admin
```

2021-08-31 12:41 UTC, oura-hideyoshi commented
コンフリクト解消しました

2021-09-01 10:27 UTC, AkashiTakumi approved these changes
オッケーかな
山名が見てOKならマージしてください

2021-09-02 10:19 UTC, merged