controllerから渡されたspotListを表示
Kobe-Spiral-2021-GroupA/santa-sanda-stamp-rally pull request #102
Opened 2021-08-19 10:06 UTC by oura-hideyoshi

## Issue

\#78

## 概要

```Markdown
変更点や補足、レビュー時に特に見てほしい点などを記載
```

## PR 作成時のチェック項目

- [ ] PR 名は issue 名と同じにした
- [ ] 担当者として Assignees を設定した
- [ ] レビューを希望する人に Reviewers を設定した
- [ ] Labels から "PR: Main" ラベルを選択した

2021-08-30 17:08 UTC, AkashiTakumi commented
これはどう動作確認したらいいですか？

2021-08-31 02:05 UTC, oura-hideyoshi commented
@AkashiTakumi 
> これはどう動作確認したらいいですか？


1. 管理者画面かrestcontrollerでスポットを作成
2. その後、mainページで作成したスポットがマップに表示されていることを確認

2021-09-01 10:42 UTC, AkashiTakumi requested changes
main画面いったときに受け取るQuestMapがnullになるんやけどこれって#101のPRで登録した後に動作確認したほうがいいんかな

2021-09-01 10:57 UTC, AkashiTakumi approved these changes
動作確認しました！
オッケーです！

2021-09-02 10:33 UTC, merged