MapServiceの実装
Kobe-Spiral-2021-GroupA/santa-sanda-stamp-rally pull request #32
Opened 2021-08-10 00:47 UTC by narimatsutomoki

## Issue

\#

## 概要

```Markdown
変更点や補足、レビュー時に特に見てほしい点などを記載
```

## PR 作成時のチェック項目

- [x] PR 名は issue 名と同じにした
- [x] 担当者として Assignees を設定した
- [x] レビューを希望する人に Reviewers を設定した
- [x] Labels から "PR: Main" ラベルを選択した

2021-08-10 00:49 UTC, onion35 commented
次のissueからは[開発フロー](https://docs.google.com/document/d/1-ShHn9qCDE7thSqP2eYWIPBavv17e4GF3iu6O7L4WKY/edit#heading=h.oeeo8ktsdjhy)のドキュメントに沿ってブランチを切るなど進めてもらえたら助かります！
今からレビューします！

2021-08-10 00:56 UTC, onion35 commented on src/main/java/jp/kobespiral/santasandastamprally/dto/MapForm.java
> +    Long mid; //マップID
変数名は基本的に省略しないで記述してもらいたいです！
今回の場合はmapIdでお願いします！

2021-08-10 01:10 UTC, onion35 commented
test

2021-08-10 01:24 UTC, onion35 commented on src/main/java/jp/kobespiral/santasandastamprally/dto/MapForm.java
> +        Map map = new Map();
CC: @AkashiTakumi
`map.setName(name)`や`map.setCreatedAt()`など、Entityで`nullable = false`なものはセットしなければならないかと思ったのですが不要ですか？

2021-08-10 01:25 UTC, onion35 commented on src/main/java/jp/kobespiral/santasandastamprally/service/MapService.java
> +    public void deleteMap(){
deleteMapが重複しているので、削除をお願いします。

2021-08-10 01:26 UTC, onion35 requested changes
一旦以上になります！
あとは明石に任せます。

2021-08-10 03:00 UTC, onion35 commented
@narimatsutomoki 
コンフリクトが起きているので、VSCodeでこのブランチに最新のbackendブランチをマージしてpushしてください！

2021-08-10 05:04 UTC, AkashiTakumi reviewed
レビューしておきました
変更よろしくです

2021-08-10 05:04 UTC, AkashiTakumi commented on src/main/java/jp/kobespiral/santasandastamprally/dto/MapForm.java
> +        Map map = new Map();
私は普段setするなあ
ここでやっといたほうがserviceのコードがキレイになる気がする

2021-08-10 05:04 UTC, AkashiTakumi commented on src/main/java/jp/kobespiral/santasandastamprally/service/MapService.java
> +    }
deleteMapってこれは論理削除じゃないっけ？
これだと物理削除になっちゃうので，deleteAtとかdeleteByに情報をsetしてsaveでお願いします

2021-08-10 05:28 UTC, narimatsutomoki commented
修正しました！

2021-08-10 06:09 UTC, onion35 commented
@narimatsutomoki 
ありがとうございます！
この画面右上のReviewersのところでリロードマークから再レビューをリクエストしてください！
そしたら通知がくるので！

2021-08-10 06:32 UTC, onion35 requested changes
再レビューが完了したので確認お願いします！

2021-08-10 06:32 UTC, onion35 commented on src/main/java/jp/kobespiral/santasandastamprally/controller/SandaQuestRestController.java
> +package jp.kobespiral.santasandastamprally.controller;
このファイルはおそらく別issueのものかと思われますので、
このブランチでは削除してコミット&pushお願いします
(REST APIブランチで消えないように注意を！)

2021-08-10 06:32 UTC, onion35 commented on src/main/java/jp/kobespiral/santasandastamprally/dto/MapForm.java
> +
createdByのメンバ変数を追加して、toEntity内でsetCreatedBy/setUpdatedByを叩く必要があるかと思います！

2021-08-10 06:32 UTC, onion35 commented on src/main/java/jp/kobespiral/santasandastamprally/service/MapService.java
> +    public void deleteMap(Long mapId){
引数にadminIdを追加して、deletedByにセットする処理を追加お願いします！

2021-08-10 06:43 UTC, AkashiTakumi requested changes
明石レビューしました
Mappingはget以外基本postでいいです．
putとかdeleteはThymeleafがサポートしてなくて，JSで実装しなきゃやからちょっと実装コストかかっちゃうので．
取得するやつはget，それ以外DBに変更加えるやつはpostって思っとけばいいです．
deleteメソッドのリターンはコメント参考に適当に変えてください

2021-08-10 06:43 UTC, AkashiTakumi commented on src/main/java/jp/kobespiral/santasandastamprally/controller/SandaQuestRestController.java
> +        return true;
ここ必ずtrueが返ってくるのちょっと気持ち悪い
それやったらserviceの返り値をvoidからUserに変えるか，ここのretuenをvoidにしていいと思う

2021-08-10 06:43 UTC, AkashiTakumi commented on src/main/java/jp/kobespiral/santasandastamprally/controller/SandaQuestRestController.java
> +
ユーザの一覧を返すコントローラの実装

2021-08-10 06:43 UTC, AkashiTakumi commented on src/main/java/jp/kobespiral/santasandastamprally/controller/SandaQuestRestController.java
> +    @PutMapping("/users/{userId}")
post

2021-08-10 06:43 UTC, AkashiTakumi commented on src/main/java/jp/kobespiral/santasandastamprally/controller/SandaQuestRestController.java
> +    @DeleteMapping("/users/{userId}")
post

2021-08-10 06:43 UTC, AkashiTakumi commented on src/main/java/jp/kobespiral/santasandastamprally/controller/SandaQuestRestController.java
> +    @PutMapping("/maps/{mapId}")
post

2021-08-10 06:43 UTC, AkashiTakumi commented on src/main/java/jp/kobespiral/santasandastamprally/controller/SandaQuestRestController.java
> +    @DeleteMapping("/maps/{mapId}")
post

2021-08-10 06:43 UTC, AkashiTakumi commented on src/main/java/jp/kobespiral/santasandastamprally/controller/SandaQuestRestController.java
> +        return true;
ここのtrueも同様の理由でちょっと気持ち悪い

2021-08-11 02:02 UTC, AkashiTakumi commented
一旦さこーのレビュー待ちということでコメントしておきます

2021-08-11 02:10 UTC, AkashiTakumi commented
RESTAPIはemptyになってへん？
もう一個のRESTのIssueでPR出してくれてると思う

2021-08-11 03:14 UTC, AkashiTakumi requested changes
MapFormの属性の型一つだけ更新してください．
あと，このブランチではSandaQuestRestController.javaを消してからcommitとpushお願いします．

2021-08-11 03:14 UTC, AkashiTakumi commented on src/main/java/jp/kobespiral/santasandastamprally/dto/MapForm.java
> +    double rangeLimit; // 位置情報の誤差
ここDoubleにお願いします

2021-08-11 04:25 UTC, onion35 approved these changes

2021-08-11 05:21 UTC, AkashiTakumi requested changes
唯一のisEnabledなものを取るやつ作ってください
なんどもすまん～

2021-08-11 08:28 UTC, AkashiTakumi approved these changes
オッケーです！
お疲れ様！！

2021-08-11 08:36 UTC, merged