SpotServiceの実装
Kobe-Spiral-2021-GroupA/santa-sanda-stamp-rally pull request #36
Opened 2021-08-10 04:40 UTC by onion35

## Issue

\#23

## 概要

```Markdown
変更点や補足、レビュー時に特に見てほしい点などを記載
```

- SpotServiceの実装
- SpotFormの実装
- Spotエンティティのフォーマット修正

## PR 作成時のチェック項目

- [x] PR 名は issue 名と同じにした
- [x] 担当者として Assignees を設定した
- [x] レビューを希望する人に Reviewers を設定した
- [ ] Labels から "PR: Main" ラベルを選択した

2021-08-10 05:33 UTC, AkashiTakumi approved these changes
オッケーです！
マージします

2021-08-10 06:16 UTC, onion35 commented
後ほどメソッド追加予定

2021-08-11 01:59 UTC, onion35 commented
@AkashiTakumi 
一旦push
足りなければまた追加します

2021-08-11 02:05 UTC, AkashiTakumi requested changes
一つだけServiceにコメント残してます

2021-08-11 02:05 UTC, AkashiTakumi commented on src/main/java/jp/kobespiral/santasandastamprally/service/SpotService.java
> +    public Spot updateSpot(Long adminId, Long spotId, UpdateSpotDto spotDto) {
ここの引数のadminId死んでへん？

2021-08-11 02:12 UTC, AkashiTakumi approved these changes
修正ありがとう！！

2021-08-11 02:56 UTC, AkashiTakumi commented
マージしよう思ったら，さっきSpotEntityの緯度経度をdoubleからDoubleに変えたらコンフリクト起こしてもうたので修正必要かも
こっち来てからでもやっていただければ

2021-08-11 03:05 UTC, onion35 commented
コンフリクト解消しました！

2021-08-11 03:06 UTC, AkashiTakumi commented
じゃあマージしまーす

2021-08-11 03:07 UTC, merged