UserServiceの実装
Kobe-Spiral-2021-GroupA/santa-sanda-stamp-rally pull request #41
Opened 2021-08-10 05:44 UTC by narimatsutomoki

## Issue

\#

## 概要

```Markdown
変更点や補足、レビュー時に特に見てほしい点などを記載
```

## PR 作成時のチェック項目

- [x] PR 名は issue 名と同じにした
- [x] 担当者として Assignees を設定した
- [x] レビューを希望する人に Reviewers を設定した
- [x] Labels から "PR: Main" ラベルを選択した

2021-08-10 06:19 UTC, AkashiTakumi requested changes
とりあえず実装はオッケー
userform実装して，そっちも確認してからマージします

2021-08-10 06:25 UTC, AkashiTakumi requested changes
レビュー終わりました．
さっきserviceは大丈夫そうって言ったけど，一つだけ機能追加お願い

2021-08-10 06:25 UTC, AkashiTakumi commented on src/main/java/jp/kobespiral/santasandastamprally/dto/UserForm.java
> +        user.setLastLoginAt(date);
登録するときはnullでいいかも
ログイン処理を行うときに，このユーザのこのカラムにセットしてsaveすれば

2021-08-10 06:25 UTC, AkashiTakumi commented on src/main/java/jp/kobespiral/santasandastamprally/service/UserService.java
> +        return userRepo.save(user);
更新するときにuser内のupdate周りの値を更新する必要がある
deleteの時と同じ要領でお願いします

2021-08-10 06:55 UTC, onion35 commented on src/main/java/jp/kobespiral/santasandastamprally/dto/UserForm.java
> +        user.setLastLoginAt(date);
EntityでlastLoginAtがnullable=falseやから、エンティティの修正をするかこのままかどっちがいいでしょう

2021-08-10 06:56 UTC, onion35 approved these changes
最終ログインの部分が解決すればマージでOKだと思います！

2021-08-11 02:27 UTC, AkashiTakumi requested changes
entityまわりのエラーめんどくさいですが，修正お願いします．

2021-08-11 02:27 UTC, AkashiTakumi commented on src/main/java/jp/kobespiral/santasandastamprally/service/UserService.java
> +        User user = userRepo.findById(userId).orElseThrow();
Repositoryのキーと型があってないエラー
変更をbackendからpullしたのち修正してください

2021-08-11 02:27 UTC, AkashiTakumi commented on src/main/java/jp/kobespiral/santasandastamprally/dto/UserForm.java
> +        user.setUserId(userId.toString());
UserのuserIdがUUIDだよのエラー
こちらも同様にBackendからpullしたのちに修正してください

2021-08-11 03:15 UTC, AkashiTakumi approved these changes
オッケー！直ってます

2021-08-11 03:16 UTC, merged