MapまわりのRESTAPI実装
Kobe-Spiral-2021-GroupA/santa-sanda-stamp-rally pull request #44
Opened 2021-08-10 07:42 UTC by narimatsutomoki

## Issue

\#14

## 概要

```Markdown
変更点や補足、レビュー時に特に見てほしい点などを記載
```

## PR 作成時のチェック項目

- [x] PR 名は issue 名と同じにした
- [x] 担当者として Assignees を設定した
- [x] レビューを希望する人に Reviewers を設定した
- [ ] Labels から "PR: Main" ラベルを選択した

2021-08-11 05:52 UTC, onion35 commented
@narimatsutomoki 
コンフリクトの解消をお願いします!

2021-08-11 07:57 UTC, onion35 requested changes
一旦以上になります！

2021-08-11 07:57 UTC, onion35 commented on src/main/java/jp/kobespiral/santasandastamprally/controller/SandaQuestRestController.java
>  import org.springframework.web.bind.annotation.GetMapping;
他のREST APiと同様に別ファイルに分離お願いします！

2021-08-11 07:57 UTC, onion35 commented on src/main/java/jp/kobespiral/santasandastamprally/dto/MapForm.java
> +package jp.kobespiral.santasandastamprally.dto;
MapServiceの方でCreate/Updateで分けたりしてるので、そっちがマージされたらbackendを取り込んで修正お願いします！

2021-08-11 07:57 UTC, onion35 commented on src/main/java/jp/kobespiral/santasandastamprally/service/MapService.java
> +package jp.kobespiral.santasandastamprally.service;
これも同様にMapServiceのPRがマージされたあとに取り込んでください

2021-08-12 01:38 UTC, onion35 requested changes
OKです！

2021-08-12 01:39 UTC, onion35 approved these changes

2021-08-12 01:55 UTC, AkashiTakumi approved these changes
ほいオッケー

2021-08-12 01:56 UTC, merged