進捗管理のRESTAPIを実装する #22
Kobe-Spiral-2021-GroupA/santa-sanda-stamp-rally pull request #53
Opened 2021-08-11 01:17 UTC by ozono8810

## Issue

\#22

## 概要

### ProgressRestControllerを追加
- ローカルで動作確認済み
またコミットログいっぱいになってしまいました．
変更は「削除されたデータも表示できるように変更」からです．

## PR 作成時のチェック項目

- [x] PR 名は issue 名と同じにした
- [x] 担当者として Assignees を設定した
- [x] レビューを希望する人に Reviewers を設定した
- [x] Labels から "PR: Main" ラベルを選択した

2021-08-11 04:48 UTC, onion35 commented
@ozono8810 
コンフリクトの解消をお願いします

2021-08-11 06:22 UTC, ozono8810 commented
コンフリクト直しました．

2021-08-11 06:27 UTC, ozono8810 commented
新しくなったbackendとのコンフリクトを解消しました．

2021-08-11 06:54 UTC, onion35 requested changes
レビューしました
確認よろしくお願いします！

2021-08-11 06:54 UTC, onion35 commented on src/main/java/jp/kobespiral/santasandastamprally/controller/ProgressRestController.java
> +@RequestMapping("/api/progress")
/api/progress
として、下のすべてのパスから/progressを削除してください！

2021-08-11 06:54 UTC, onion35 commented on src/main/java/jp/kobespiral/santasandastamprally/service/ProgressService.java
> +        if(getProgress(progress.getMapId(), progress.getUserId()) == null) {
getProgressはnullを返さないので、分岐は不要かと思います！

2021-08-11 06:54 UTC, onion35 commented on src/main/java/jp/kobespiral/santasandastamprally/controller/ProgressRestController.java
> +    // マップIDとユーザIDから進捗を取得する
serviceへの質問かもしれないのですが、getProgress(progressId)との違いってありますか？
言い換えると、同じmapIdとuserIdの組み合わせで異なるprogressIdである可能性ってありますか？

2021-08-11 06:55 UTC, AkashiTakumi approved these changes
おっけーです

2021-08-11 09:18 UTC, AkashiTakumi commented on src/main/java/jp/kobespiral/santasandastamprally/controller/ProgressRestController.java
> +    // マップIDとユーザIDから進捗を取得する
RestAPIやし，別にある分には良いんちゃうかな？
APIやし，違うkeyでとれることに意味があると思う

2021-08-11 09:29 UTC, ozono8810 commented
よろしくお願いします．

2021-08-12 00:28 UTC, onion35 approved these changes
ProgressServiceのブランチがbackendにマージされ次第、このブランチに取り込んでpushしてください！
あとはOKだと思います！

2021-08-12 01:24 UTC, AkashiTakumi approved these changes
オッケー！
もし指定マップの指定ユーザの進捗とるやつが上手く動かなかったらその時考えましょう

2021-08-12 02:17 UTC, AkashiTakumi approved these changes
オッケー！
お疲れ様です

2021-08-12 02:18 UTC, merged