SpotのRESTAPIを実装
Kobe-Spiral-2021-GroupA/santa-sanda-stamp-rally pull request #71
Opened 2021-08-11 07:31 UTC by narimatsutomoki

## Issue

\#24

## 概要

```Markdown
変更点や補足、レビュー時に特に見てほしい点などを記載
```

## PR 作成時のチェック項目

- [x] PR 名は issue 名と同じにした
- [x] 担当者として Assignees を設定した
- [x] レビューを希望する人に Reviewers を設定した
- [ ] Labels から "PR: Main" ラベルを選択した

2021-08-11 07:40 UTC, onion35 requested changes
一旦レビューしました。
パス関連などでまだ追加事項はあると思います！

2021-08-11 07:40 UTC, onion35 commented on src/main/java/jp/kobespiral/santasandastamprally/controller/SpotRestController.java
> +@RequestMapping("/api/spot")
ここで/spi/spotとしているので、それぞれのマッピングから/spotsは消して大丈夫！

2021-08-11 07:40 UTC, onion35 commented on src/main/java/jp/kobespiral/santasandastamprally/controller/SpotRestController.java
> +    Spot createUser(@RequestBody CreateSpotDto SpotDto){
createSpotFormを作って引数はCreateSpotForm SpotFormとして、createSpotDtoに変換する処理を挟んでほしいです！
最新のbackendをマージしてきてTaskのコントローラ(明石が作った)を見てもらったらわかるかと

2021-08-11 09:24 UTC, AkashiTakumi requested changes
さこーと同じ感じ
他は大丈夫そうなので修正お願いします

2021-08-11 09:24 UTC, AkashiTakumi commented on src/main/java/jp/kobespiral/santasandastamprally/controller/SpotRestController.java
> +    void deleteuser(@PathVariable Long adminId,@PathVariable Long spotId){
uを大文字にしてください

2021-08-12 00:53 UTC, onion35 approved these changes
OKです！

2021-08-12 01:36 UTC, AkashiTakumi approved these changes
とりあえずはオッケーです
もしform周りで型の不具合出たらすぐ修正Issue上げます

2021-08-12 01:44 UTC, merged