ProgressServiceにスコアを取得する機能を追加する #56
Kobe-Spiral-2021-GroupA/santa-sanda-stamp-rally pull request #72
Opened 2021-08-11 08:01 UTC by ozono8810

## Issue

\#56

## 概要

ProgressServiceにスコアを取得する機能を追加する

## PR 作成時のチェック項目

- [x] PR 名は issue 名と同じにした
- [x] 担当者として Assignees を設定した
- [x] レビューを希望する人に Reviewers を設定した
- [x] Labels から "PR: Main" ラベルを選択した

2021-08-11 08:36 UTC, onion35 requested changes
レビューしました
確認お願いします！

2021-08-11 08:36 UTC, onion35 commented on src/main/java/jp/kobespiral/santasandastamprally/service/ProgressService.java
> +            if(spotLogService.getSpotLogs(spotId, userId) != null) score++;
空のリストが返ってくるとのことなので、List`spotLogService.getSpotLogs(spotId, userId) != null`ではなく`spotLogService.getSpotLogs(spotId, userId).length != 0`の方がよいかと思います！
下のtaskの方も同様です！！

2021-08-11 09:30 UTC, ozono8810 commented
#22　とコンフリクトが起こるかもしれないです．

2021-08-12 00:03 UTC, onion35 approved these changes
良いと思います！

2021-08-12 00:17 UTC, AkashiTakumi requested changes
修正お願いします

2021-08-12 00:17 UTC, AkashiTakumi commented on src/main/java/jp/kobespiral/santasandastamprally/service/ProgressService.java
>          return progressRepository.save(progress);
取得なのにsaveしてええの？？

2021-08-12 00:45 UTC, AkashiTakumi approved these changes
オッケーです
お疲れ様！

2021-08-12 00:47 UTC, merged