距離を測ってspotlogの保存を行うサービスの実装 #67
Kobe-Spiral-2021-GroupA/santa-sanda-stamp-rally pull request #73
Opened 2021-08-11 08:04 UTC by AkashiTakumi

## Issue

\#67

## 概要

- 現在地と目的地の距離を測るGpsServiceの実装
- spotの保存を行うメソッドの更新

## PR 作成時のチェック項目

- [ ] PR 名は issue 名と同じにした
- [ ] 担当者として Assignees を設定した
- [ ] レビューを希望する人に Reviewers を設定した
- [ ] Labels から "PR: Main" ラベルを選択した

2021-08-11 08:22 UTC, onion35 requested changes
レビューしました
確認お願いします！

2021-08-11 08:22 UTC, onion35 commented on src/main/java/jp/kobespiral/santasandastamprally/dto/LatAndLngDto.java
> +public class LatAndLngDto {
【修正依頼】
省略形はいやです！
変数にカーソルを合わせてF2キーを押すと、関連するimportとかも全部リファクタリングしてくれるのでオススメ

2021-08-11 08:22 UTC, onion35 commented on src/main/java/jp/kobespiral/santasandastamprally/service/GpsService.java
> +    @Autowired
【質問】
これってどういう役割ですか？

2021-08-11 08:22 UTC, onion35 commented on src/main/java/jp/kobespiral/santasandastamprally/service/GpsService.java
> +     * @param nowPoint 現在地
【提案】
nowよりcurrentの方がいい気がします

2021-08-11 08:30 UTC, AkashiTakumi commented on src/main/java/jp/kobespiral/santasandastamprally/service/GpsService.java
> +    @Autowired
なんか追加しようとした痕跡ですねこれ
消しました

2021-08-11 08:52 UTC, onion35 commented on src/main/java/jp/kobespiral/santasandastamprally/service/SpotLogService.java
> +        LatitudeAndLongitudeDto nowPoint = new LatitudeAndLongitudeDto();
ここも同様にcurrentPointで！

2021-08-11 08:56 UTC, onion35 requested changes
以上です！

2021-08-12 00:20 UTC, onion35 approved these changes
OKです

2021-08-12 00:20 UTC, merged

2021-08-12 00:24 UTC, onion35 requested changes
レビューしました
確認お願いします！